:bulb: (#11) Adicionando validações de entradas
UnBArqDsw2022-1/2022.1_G2_DonAct pull request #33
Opened 2022-08-24 04:21 UTC by antoniotoineto

Nessa PR estarei adicionando as validações de entradas dos dados do cadastro de ONG. Nesse caso, as validações estão no back-end

## Types of changes

What types of changes does your code introduce to <repo_name>?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the CONTRIBUTING.md doc.
- [ ] I have added necessary documentation (if appropriate).
- [ ] Any dependent changes have been merged and published in downstream modules.

## Further comments

Eu não consegui fazer a validação do email. Tive dificuldade com regex nessa parte.

2022-08-24 15:02 UTC, victorear05 commented on desenvolvimento/DonAct-API/src/controllers/ONGController.js
> +      console.log(req.body.cnpj)
Remover os console.log

2022-08-24 15:05 UTC, victorear05 commented on desenvolvimento/DonAct-API/src/controllers/ONGController.js
> +        //case 8:
Não está verificando se o e-mail é válido. Aproveitar para adicionar verificação de se o e-mail já não foi cadastrado.

2022-08-24 15:06 UTC, victorear05 commented on desenvolvimento/DonAct-API/src/controllers/ONGController.js
>      editar: async (req, res) => {
Adicionar verficações para editar cadastro também

2022-08-24 15:07 UTC, victorear05 requested changes
- [x] Adicionar validação de dados para edição de cadastros também
- [x] Remover os console.log
- [x] Não está verificando se o e-mail é válido.
- [x] Adicionar verificação de se o e-mail já não foi cadastrado.
- [x] Adicionar verificação de se telefone já não foi cadastrado.
- [x] Adicionar verificação de se o e-mail do responsável já não foi cadastrado.

2022-08-24 18:20 UTC, antoniotoineto commented
Adicionei todas as alterações, com exceção da verificação do email, o qual não consegui fazer

Alinhado com Dudu, ele vai tentar fazer essa parte da validação de email e merjar a branch com a main

2022-08-25 13:09 UTC, victorear05 approved these changes

2022-08-27 15:17 UTC, yandrade1305 commented
@antoniotoineto @victorear05 Teve conflito, por favor arrumem!

2022-08-30 02:22 UTC, victorear05 commented
> @antoniotoineto @victorear05 Teve conflito, por favor arrumem! Dá uma olhada nessa validação, talvez seja mais simples: https://sequelize.org/docs/v6/core-concepts/validations-and-constraints/

Mano de fato, é bem mais simples assim... Fiz dessa forma, fica até mais elegante tbm.

2022-08-30 12:57 UTC, yandrade1305 approved these changes
Parabéns você conseguiu 😄 🏆

2022-08-30 12:57 UTC, merged